### ISSUE TITLE
`sys/features.h` not found when building with `musl`.

### ISSUE THREAD

**Issue by StefanJum** [unikraft/lib-libcxx#7]
Building with [Musl](https://github.com/unikraft/lib-musl) fails on [this line](https://github.com/unikraft/lib-libcxx/blob/staging/include/features.h#L37), since there is no `sys/features.h` within Musl source files.

There is a [`features.h` header file](https://git.musl-libc.org/cgit/musl/tree/include/features.h?h=v1.1.19&id=55df09bfccbfe21fc9dd7d8f94550c0ff25ace04) that can be used as a replacement for the [newlib's `sys/features.h`](https://github.com/bminor/newlib/blob/master/newlib/libc/include/sys/features.h)

```make
make[3]: *** [unikraft/musl-test/unikraft-musl/unikraft/support/build/Makefile.build:49: unikraft/musl-test/unikraft-musl/apps/app-helloworld-cpp/build/libkvmplat/cpu_native.common.o] Error 1
In file included from unikraft/musl-test/unikraft-musl/apps/app-helloworld-cpp/build/libmusl/include/dirent/include/string.h:8,
                 from unikraft/musl-test/unikraft-musl/apps/app-helloworld-cpp/build/libcxx/origin/libcxx-7.0.0.src/include/string.h:61,
                 from unikraft/musl-test/unikraft-musl/unikraft/plat/kvm/x86/setup.c:29:
unikraft/musl-test/unikraft-musl/libs/libcxx/include/features.h:37:10: fatal error: sys/features.h: No such file or directory
   37 | #include <sys/features.h>
```

**Comment by razvand** [comment]
Solved by #9
